baseURL = "https://blog.ohr486.net/"
languageCode = "ja"
title = "ohr486's blog"
hasCJKLanguage = true
theme = "uBlogger"

[params]
    version = "2.0.X"
    defaultTheme = "light"
    gitRepo = "https://github.com/ohr486/blog.ohr486.net"

    [params.social]
        GitHub = "ohr486"
        Twitter = "ohrdev"
        Email = "ohr486@gmail.com"
        RSS = true

    [params.header]

    [params.footer]
        enable = true
        custom = ""
        hugo = true
        copyright = true
        author = true
        since = 2021
        icp = ""
        license = ""

    [params.page]
        [params.page.share]
            enable = true
            Twitter = true
            Facebook = true
        [params.page.seo]

    [params.seo]
        images = "https://blog.ohr486.net/images/blog-logo.jpg"
        thumbnailUrl = "https://blog.ohr486.net/images/blog-logo.jpg"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        noClasses = false

[author]
    nickname = "ohr486"

[Permalinks]
    posts = ":year/:month/:day/:filename"

[deployment]
    [[deployment.targets]]
        name = "blog.ohr486.net"
        URL = "s3://blog.ohr486.net?region=ap-northeast-1"
        cloudFrontDistributionID = "E348PDJARCQT4X"

    [[deployment.matchers]]
        pattern = "^.+\\.(js|css|svg|ttf)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip = true

    [[deployment.matchers]]
        pattern = "^.+\\.(png|jpg)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip = false

    [[deployment.matchers]]
        pattern = "^sitemap\\.xml$"
        contentType = "application/xml"
        gzip = true

    [[deployment.matchers]]
        pattern = "^.+\\.(html|xml|json)$"
        gzip = true
