baseURL = "https://blog.ohr486.net/"
languageCode = "ja"
title = "ohr486's blog"

theme = "uBlogger"

[params]
  version = "2.0.X"

[menu]
    [[menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1
    [[menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
    [[menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3

[markup]
  [markup.highlight]
    noClasses = false