version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: env
      - run:
          command: ls -alh
      - slack/notify:
          event: always

workflows:
  test-and-deploy:
    jobs:
      - build:
          context: ohr486-circleci-notification

