[[main]]
    # Top-level menu entry
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

[[main]]
    identifier = "categories-all"
    name = "All"
    url = "/categories"
    parent = "categories"
    weight = 3

[[main]]
    identifier = "categories-tech"
    name = "Tech"
    url = "/categories/tech"
    parent = "categories"
    weight = 4

[[main]]
    identifier = "categories-book-review"
    name = "Book Review"
    url = "/categories/book-review"
    parent = "categories"
    weight = 5

[[main]]
    identifier = "categories-etc"
    name = "etc"
    url = "/categories/etc"
    parent = "categories"
    weight = 6



[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 7

[[main]]
    identifier = "tags-all"
    name = "All"
    url = "/tags/"
    parent = "tags"
    weight = 8

[[main]]
    identifier = "tags-aws"
    name = "AWS"
    url = "/tags/aws/"
    parent = "tags"
    weight = 9

[[main]]
    identifier = "tags-elixir"
    name = "Elixir"
    url = "/tags/elixir/"
    parent = "tags"
    weight = 10

[[main]]
    identifier = "tags-erlang"
    name = "Erlang"
    url = "/tags/erlang/"
    parent = "tags"
    weight = 11

[[main]]
    identifier = "tags-advent-calendar"
    name = "Advent Calendar"
    url = "/tags/advent-calendar/"
    parent = "tags"
    weight = 12

[[main]]
    identifier = "tags-life"
    name = "Life"
    url = "/tags/life/"
    parent = "tags"
    weight = 13







[[main]]
    # Top-level menu entry
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 8

#[[main]]
#    # Top-level menu entry
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 9

